/**
 * Build: TypeScript → hashed, minified ES modules (face detector split into its own lazy file),
 * index.html from the template, service worker with the exact file list, version.json.
 *
 *   node build.mjs                  → dist/
 *   node build.mjs --out ..         → dist/, then copied into the GitHub Pages repo (this folder is <repo>/app-src)
 *                                      (keeps the repo's config.js, download/, .well-known/, README.md)
 */
import * as esbuild from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.dirname(new URL(import.meta.url).pathname);
const DIST = path.join(ROOT, 'dist');
const pkg = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'));
const VERSION = pkg.version;
const NOTES = pkg.releaseNotes || '';
const outArg = process.argv.indexOf('--out');
const REPO = outArg > 0 ? path.resolve(process.argv[outArg + 1]) : null;
const KEEP_IN_REPO = new Set(['.git', '.gitignore', 'app-src', 'config.js', 'download', '.well-known', 'README.md', '.nojekyll', 'CNAME']);

fs.rmSync(DIST, { recursive: true, force: true });
fs.mkdirSync(DIST, { recursive: true });

/* 1) app: code-split ES modules with content hashes */
const app = await esbuild.build({
  entryPoints: { main: 'src/main.ts', styles: 'src/styles.css' },
  absWorkingDir: ROOT,
  bundle: true,
  splitting: true,
  format: 'esm',
  target: ['es2020', 'chrome80', 'safari14'],
  minify: true,
  legalComments: 'none',
  outdir: path.join(DIST, 'assets'),
  entryNames: '[name]-[hash]',
  chunkNames: '[name]-[hash]',
  metafile: true,
  define: { __APP_VERSION__: JSON.stringify(VERSION) },
  logLevel: 'warning'
});

const outputs = Object.entries(app.metafile.outputs).map(([file, o]) => ({
  rel: path.relative(DIST, path.join(ROOT, file)).split(path.sep).join('/'),
  bytes: o.bytes,
  entry: o.entryPoint || ''
}));
const js = outputs.find(o => o.entry === 'src/main.ts').rel;
const css = outputs.find(o => o.entry === 'src/styles.css' && o.rel.endsWith('.css')).rel;
// esbuild also emits an empty JS stub for the CSS entry — drop it
for (const o of outputs.filter(o => o.entry === 'src/styles.css' && o.rel.endsWith('.js'))) fs.rmSync(path.join(DIST, o.rel));
const assets = outputs.filter(o => !(o.entry === 'src/styles.css' && o.rel.endsWith('.js'))).map(o => o.rel);

/* 2) static files */
fs.cpSync(path.join(ROOT, 'public'), DIST, { recursive: true });
const walk = dir => fs.readdirSync(dir, { withFileTypes: true })
  .flatMap(d => d.isDirectory() ? walk(path.join(dir, d.name)) : [path.join(dir, d.name)]);
const rel = f => path.relative(DIST, f).split(path.sep).join('/');
const models = [...walk(path.join(DIST, 'models')), ...walk(path.join(DIST, 'wasm'))].map(rel);

/* 3) index.html (+ preload of the small shared chunks main.js imports, so they load in parallel) */
const mainMeta = Object.entries(app.metafile.outputs).find(([, o]) => o.entryPoint === 'src/main.ts')[1];
const preloads = mainMeta.imports.filter(i => i.kind === 'import-statement')
  .map(i => `<link rel="modulepreload" href="${path.relative(DIST, path.join(ROOT, i.path)).split(path.sep).join('/')}">`);
const html = fs.readFileSync(path.join(ROOT, 'src/index.template.html'), 'utf8')
  .replace('<link rel="modulepreload" href="%JS%">', ['<link rel="modulepreload" href="%JS%">', ...preloads].join('\n  '))
  .replaceAll('%CSS%', css).replaceAll('%JS%', js).replaceAll('%VERSION%', VERSION);
fs.writeFileSync(path.join(DIST, 'index.html'), html);

/* 4) service worker with the exact file list */
const precache = [...assets, ...models, `config.js?v=${VERSION}`, 'manifest.webmanifest',
  'icons/icon-192.png', 'icons/icon-512.png', 'icons/apple-touch-icon.png'];
await esbuild.build({
  entryPoints: ['src/sw.ts'],
  absWorkingDir: ROOT,
  bundle: true,
  format: 'iife',
  target: ['es2020'],
  minify: false,
  outfile: path.join(DIST, 'sw.js'),
  banner: { js: `/* AAP Attendance service worker v${VERSION} — generated by build.mjs */` },
  define: { __APP_VERSION__: JSON.stringify(VERSION), __PRECACHE__: JSON.stringify(precache) },
  logLevel: 'warning'
});

/* 5) version.json (keeps the APK numbers that are already published) */
let prev = {};
if (REPO) { try { prev = JSON.parse(fs.readFileSync(path.join(REPO, 'version.json'), 'utf8')); } catch { /* first build */ } }
fs.writeFileSync(path.join(DIST, 'version.json'), JSON.stringify({
  web: VERSION, notes: NOTES, minApk: prev.minApk ?? 1, latestApk: prev.latestApk ?? 1
}, null, 1) + '\n');

/* 6) report */
const kb = b => (b / 1024).toFixed(1) + ' KB';
console.log(`AAP Attendance v${VERSION}`);
for (const o of outputs.filter(o => fs.existsSync(path.join(DIST, o.rel)))) console.log('  ' + o.rel.padEnd(42) + kb(o.bytes));
console.log('  precache: ' + precache.length + ' files');

/* 7) copy into the GitHub Pages repo */
if (REPO) {
  for (const name of fs.readdirSync(REPO)) {
    if (!KEEP_IN_REPO.has(name)) fs.rmSync(path.join(REPO, name), { recursive: true, force: true });
  }
  for (const name of fs.readdirSync(DIST)) {
    if (name === 'config.js' && fs.existsSync(path.join(REPO, 'config.js'))) continue; // server URL lives in the repo
    fs.cpSync(path.join(DIST, name), path.join(REPO, name), { recursive: true });
  }
  console.log('  → copied to ' + REPO);
}
