/* AAP Attendance service worker v15.0.0 — generated by build.mjs */
"use strict";
(() => {
  // <define:__PRECACHE__>
  var define_PRECACHE_default = ["assets/main-MBK43545.js", "assets/face-api.esm-LZTKOEHZ.js", "assets/chunk-I7AUKTXE.js", "assets/styles-QT2TTEBZ.css", "models/tiny_face_detector_model-weights_manifest.json", "models/tiny_face_detector_model.bin", "wasm/tfjs-backend-wasm-simd.wasm", "wasm/tfjs-backend-wasm.wasm", "config.js?v=15.0.0", "manifest.webmanifest", "icons/icon-192.png", "icons/icon-512.png", "icons/apple-touch-icon.png"];

  // src/sw.ts
  var sw = self;
  var CACHE = "aap-attendance-15.0.0";
  var PAGE = "./";
  var ASSET_RE = /(?:src|href)="((?:assets|models|wasm)\/[^"]+|config\.js\?v=[^"]+)"/g;
  async function fromAnyCache(url) {
    return caches.match(url);
  }
  async function put(cache, url, fresh = false) {
    try {
      const hit = !fresh && await fromAnyCache(url);
      const res = hit || await fetch(url, { cache: "no-cache" });
      if (!res.ok) return false;
      await cache.put(url, res.clone());
      return true;
    } catch {
      return false;
    }
  }
  sw.addEventListener("install", (e) => {
    e.waitUntil((async () => {
      const cache = await caches.open(CACHE);
      await put(cache, PAGE, true);
      await Promise.all(define_PRECACHE_default.map((u) => put(cache, u)));
      await sw.skipWaiting();
    })());
  });
  sw.addEventListener("activate", (e) => {
    e.waitUntil((async () => {
      const keys = await caches.keys();
      await Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)));
      await sw.clients.claim();
    })());
  });
  async function refreshPage() {
    const res = await fetch(PAGE, { cache: "no-cache", credentials: "same-origin" });
    if (!res.ok) return res;
    const html = await res.clone().text();
    const cache = await caches.open(CACHE);
    const urls = Array.from(html.matchAll(ASSET_RE), (m) => m[1]);
    const ok = await Promise.all(urls.map((u) => put(cache, u)));
    if (ok.every(Boolean)) await cache.put(PAGE, res.clone());
    return res;
  }
  sw.addEventListener("fetch", (e) => {
    const req = e.request;
    const url = new URL(req.url);
    if (req.method !== "GET" || url.origin !== sw.location.origin) return;
    const path = url.pathname;
    if (path.startsWith("/download/") || path.startsWith("/.well-known/") || path.endsWith("/version.json")) return;
    if (req.mode === "navigate") {
      e.respondWith((async () => {
        const hit = await caches.match(PAGE);
        const net = refreshPage();
        if (hit) {
          e.waitUntil(net.catch(() => null));
          return hit;
        }
        return net;
      })());
      return;
    }
    e.respondWith((async () => {
      const hit = await caches.match(req);
      if (hit) return hit;
      const res = await fetch(req);
      if (res.ok && (/\/(assets|models|wasm|icons)\//.test(path) || url.search.startsWith("?v="))) {
        const copy = res.clone();
        e.waitUntil(caches.open(CACHE).then((c) => c.put(req, copy)));
      }
      return res;
    })());
  });
})();
